-- 手动应用 AddBookPurposeCategoryLink 迁移

CREATE TABLE IF NOT EXISTS "BookPurposeCategoryLinks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Purpose" integer NOT NULL,
    "CategoryId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_BookPurposeCategoryLinks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BookPurposeCategoryLinks_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS "IX_BookPurposeCategoryLinks_CategoryId" ON "BookPurposeCategoryLinks" ("CategoryId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_BookPurposeCategoryLinks_Purpose_CategoryId" ON "BookPurposeCategoryLinks" ("Purpose", "CategoryId");

-- INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES ('20260622064422_AddBookPurposeCategoryLink', '9.0.0');
