-- 手动应用 AddAccountBookCategoryLink 迁移
-- 若表已存在可跳过；若 __EFMigrationsHistory 中已有该迁移记录但表未创建，先执行本脚本再保留迁移记录

-- 创建表（若已存在会报错，可忽略）
CREATE TABLE IF NOT EXISTS "AccountBookCategoryLinks" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "AccountBookId" integer NOT NULL,
    "CategoryId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AccountBookCategoryLinks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AccountBookCategoryLinks_AccountBooks_AccountBookId" FOREIGN KEY ("AccountBookId") REFERENCES "AccountBooks" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AccountBookCategoryLinks_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE RESTRICT
);

-- 创建索引（若已存在会报错，可忽略）
CREATE UNIQUE INDEX IF NOT EXISTS "IX_AccountBookCategoryLinks_AccountBookId_CategoryId" ON "AccountBookCategoryLinks" ("AccountBookId", "CategoryId");
CREATE INDEX IF NOT EXISTS "IX_AccountBookCategoryLinks_CategoryId" ON "AccountBookCategoryLinks" ("CategoryId");

-- 若 EF 未记录该迁移，可插入迁移历史（仅当表已创建且希望 EF 认为已应用时执行）
-- INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES ('20260129050000_AddAccountBookCategoryLink', '8.0.0');
