-- 手动数据库迁移脚本
-- 执行前请先检查数据库当前状态

-- ============================================
-- 1. 添加检查约束（如果不存在）
-- ============================================
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'CK_Transaction_AccountBookId_SharedAccountBookId'
    ) THEN
        ALTER TABLE "Transactions" 
        ADD CONSTRAINT "CK_Transaction_AccountBookId_SharedAccountBookId" 
        CHECK (("AccountBookId" IS NOT NULL AND "SharedAccountBookId" IS NULL) 
               OR ("AccountBookId" IS NULL AND "SharedAccountBookId" IS NOT NULL));
    END IF;
END $$;

-- ============================================
-- 2. 添加 StartDate 和 EndDate 列到 SharedAccountBooks 表（如果不存在）
-- ============================================
DO $$
BEGIN
    -- 添加 StartDate 列
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'SharedAccountBooks' 
        AND column_name = 'StartDate'
    ) THEN
        ALTER TABLE "SharedAccountBooks" 
        ADD COLUMN "StartDate" timestamp with time zone NULL;
    END IF;

    -- 添加 EndDate 列
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'SharedAccountBooks' 
        AND column_name = 'EndDate'
    ) THEN
        ALTER TABLE "SharedAccountBooks" 
        ADD COLUMN "EndDate" timestamp with time zone NULL;
    END IF;
END $$;

-- ============================================
-- 3. 创建 TransactionImages 表（如果不存在）
-- ============================================
CREATE TABLE IF NOT EXISTS "TransactionImages" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "TransactionId" integer NOT NULL,
    "ImageUrl" character varying(500) NOT NULL,
    "SortOrder" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TransactionImages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TransactionImages_Transactions_TransactionId" 
        FOREIGN KEY ("TransactionId") 
        REFERENCES "Transactions" ("Id") 
        ON DELETE CASCADE
);

-- 创建索引（如果不存在）
CREATE INDEX IF NOT EXISTS "IX_TransactionImages_TransactionId" 
    ON "TransactionImages" ("TransactionId");

-- ============================================
-- 4. 更新迁移历史表（标记迁移为已应用）
-- ============================================
-- 注意：请根据实际情况调整迁移名称

-- 标记 AddTransactionCheckConstraint 为已应用
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20251204082603_AddTransactionCheckConstraint', '8.0.0'
WHERE NOT EXISTS (
    SELECT 1 FROM "__EFMigrationsHistory" 
    WHERE "MigrationId" = '20251204082603_AddTransactionCheckConstraint'
);

-- 标记 AddStartEndDateToSharedAccountBook 为已应用
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20251204083526_AddStartEndDateToSharedAccountBook', '8.0.0'
WHERE NOT EXISTS (
    SELECT 1 FROM "__EFMigrationsHistory" 
    WHERE "MigrationId" = '20251204083526_AddStartEndDateToSharedAccountBook'
);

-- 标记 AddTransactionImagesTable 为已应用
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20251204090010_AddTransactionImagesTable', '8.0.0'
WHERE NOT EXISTS (
    SELECT 1 FROM "__EFMigrationsHistory" 
    WHERE "MigrationId" = '20251204090010_AddTransactionImagesTable'
);










